<a href="https://colab.research.google.com/github/Dimgal2011/Learning_PyTorch/blob/master/Getting_Started.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Started


Just a quick ex. with primitives from PyTorch

**Tensors**


Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [0]:
from __future__ import print_function
import torch

Let's make a new uniinitialized matrix:

In [3]:
x = torch.empty(3, 3)
print(x)

tensor([[1.0739e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Or a randomly initialized matrix:

In [4]:
x = torch.rand(3, 3)
print(x)

tensor([[0.7666, 0.5888, 0.3533],
        [0.6160, 0.0676, 0.5289],
        [0.3679, 0.0607, 0.8977]])


Maybe the one that consists of zeros

In [7]:
x = torch.zeros(3, 3, dtype=torch.int)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


Tensor from given data:

In [8]:
x = torch.tensor([1.2, 5])
print(x)

tensor([1.2000, 5.0000])


Tensor's description:

In [18]:
x = torch.tensor([3, 3, 3])
print(x)
print(x.size())
print(x.dim())
print(x.type())


tensor([3, 3, 3])
torch.Size([3])
1
torch.LongTensor


**Operations**

In [25]:
x = x.new_ones(5, 3, dtype=torch.float)
print(x)
y = torch.rand(5, 3)
print(y)
print('\nx + y:\n', x + y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7193, 0.2910, 0.3347],
        [0.9962, 0.2266, 0.5777],
        [0.7173, 0.2822, 0.7853],
        [0.1906, 0.1557, 0.7613],
        [0.0577, 0.8090, 0.9763]])

x + y:
 tensor([[1.7193, 1.2910, 1.3347],
        [1.9962, 1.2266, 1.5777],
        [1.7173, 1.2822, 1.7853],
        [1.1906, 1.1557, 1.7613],
        [1.0577, 1.8090, 1.9763]])


In [26]:
print(torch.add(x, y))    #similar to '+'

tensor([[1.7193, 1.2910, 1.3347],
        [1.9962, 1.2266, 1.5777],
        [1.7173, 1.2822, 1.7853],
        [1.1906, 1.1557, 1.7613],
        [1.0577, 1.8090, 1.9763]])


In [27]:
res = torch.empty(5, 3)
torch.add(x, y, out=res)
print(res)

tensor([[1.7193, 1.2910, 1.3347],
        [1.9962, 1.2266, 1.5777],
        [1.7173, 1.2822, 1.7853],
        [1.1906, 1.1557, 1.7613],
        [1.0577, 1.8090, 1.9763]])


In [28]:
y.add_(x)   #addition in-place
print(y)

tensor([[1.7193, 1.2910, 1.3347],
        [1.9962, 1.2266, 1.5777],
        [1.7173, 1.2822, 1.7853],
        [1.1906, 1.1557, 1.7613],
        [1.0577, 1.8090, 1.9763]])


In [30]:
z = torch.empty(5, 3)
z.copy_(y)

tensor([[1.7193, 1.2910, 1.3347],
        [1.9962, 1.2266, 1.5777],
        [1.7173, 1.2822, 1.7853],
        [1.1906, 1.1557, 1.7613],
        [1.0577, 1.8090, 1.9763]])

In [34]:
print(y[:,2])

tensor([1.3347, 1.5777, 1.7853, 1.7613, 1.9763])


 **Resizing**

In [40]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(2, 8)
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[0.8628, 0.8412, 0.7110, 0.7521],
        [0.1154, 0.1972, 0.8325, 0.2444],
        [0.1260, 0.7007, 0.7388, 0.1912],
        [0.6737, 0.4884, 0.7450, 0.3091]])
tensor([0.8628, 0.8412, 0.7110, 0.7521, 0.1154, 0.1972, 0.8325, 0.2444, 0.1260,
        0.7007, 0.7388, 0.1912, 0.6737, 0.4884, 0.7450, 0.3091])
tensor([[0.8628, 0.8412, 0.7110, 0.7521, 0.1154, 0.1972, 0.8325, 0.2444],
        [0.1260, 0.7007, 0.7388, 0.1912, 0.6737, 0.4884, 0.7450, 0.3091]])


**NumPy**

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

In [42]:
x = torch.ones(5)
print(x)

tensor([1., 1., 1., 1., 1.])


In [44]:
y = x.numpy()
print(y)

[1. 1. 1. 1. 1.]


In [45]:
x.add_(6)     # let's see how np array changend the value
print(x)

tensor([7., 7., 7., 7., 7.])


In [46]:
print(y)

[7. 7. 7. 7. 7.]


**Converting NumPy Array to Torch Tensor**

In [47]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 6, out=a)
print(a)
print(b)

[7. 7. 7. 7. 7.]
tensor([7., 7., 7., 7., 7.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [0]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

I've no CUDA : _ [